### ISSUE TITLE
Unit tests fail for versions 1.1.15-1.1.22

### ISSUE THREAD

**Issue by aidecoe** [processone/fast_xml#24] opened 2017-03-26 20:31 UTC
Tried Erlang 18.3 and 19.2.

```
 $ make test
rebar get-deps compile
==> p1_utils (get-deps)
==> fast_xml (get-deps)
==> p1_utils (compile)
==> fast_xml (compile)
rebar -v skip_deps=true eunit
INFO:  Looking for p1_utils-.* ; found p1_utils-1.0.6 at /home/aidecoe/src/fast_xml/deps/p1_utils
INFO:  Looking for p1_utils-.* ; found p1_utils-1.0.6 at /home/aidecoe/src/fast_xml/deps/p1_utils
==> fast_xml (eunit)
INFO:  sh info:
        cwd: "/home/aidecoe/src/fast_xml"
        cmd: cp -R src/fxmlrpc.erl src/fxml_gen_pt.erl src/fxml_sup.erl src/fxml_gen.erl src/fxmlrpc_codec.erl src/fxml.erl src/fast_xml.erl src/fxml_stream.erl test/fxml_test.erl ".eunit"
Compiled src/fxml_gen_pt.erl
Compiled src/fxml_sup.erl
Compiled src/fxmlrpc.erl
Compiled src/fxml.erl
Compiled src/fast_xml.erl
Compiled src/fxml_stream.erl
Compiled src/fxmlrpc_codec.erl
Compiled test/fxml_test.erl
Compiled src/fxml_gen.erl
INFO:  Cover compiling /home/aidecoe/src/fast_xml
ERROR: eunit failed while processing /home/aidecoe/src/fast_xml: {'EXIT',
    {{case_clause,
         {error,beam_lib,
             {invalid_chunk,
                 "/home/aidecoe/src/fast_xml/.eunit/fxml_gen.beam","Abst"}}},
     [{cover,do_compile_beam1,3,[{file,"cover.erl"},{line,1533}]},
      {cover,do_compile_beam,3,[{file,"cover.erl"},{line,1472}]},
      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
      {cover,'-pmap_spawn/4-fun-0-',2,[{file,"cover.erl"},{line,2731}]}]}}
```

**Comment by zinid** [comment] 2017-03-27 06:16
Duplicate of #21

**Comment by mathiasertl** [comment] 2017-03-27 17:06
@zinid could you please open the other ticket again? I don't have the permissions. :-/

**Comment by zinid** [comment] 2017-03-27 17:18
Reopened.
I close this one.

**Closed by zinid** 2017-03-27 17:18 UTC
